import { locale, t } from "../i18n";

const labels = {
  "每一次相遇，都有新的模样。": ["A new illustration. A new encounter.", "出会うたび、新しい表情。"],
  "从联动企划到限定立绘，收藏虹咲的每一种色彩。": [
    "Collaborations, exclusive illustrations, and every shade of Nijigasaki.",
    "コラボ企画から限定イラストまで、虹ヶ咲の彩りを集めて。",
  ],
  联动一览: ["Collaborations", "コラボ一覧"],
  返回联动一览: ["Back to collaborations", "コラボ一覧へ"],
  编辑联动: ["Edit collaboration", "コラボを編集"],
  新增联动: ["New collaboration", "コラボを追加"],
  管理联动: ["Manage collaborations", "コラボを管理"],
  "标题、合作方、备注或关键词": ["Title, partner, notes, or keyword", "タイトル・コラボ先・備考・キーワード"],
  全部年份: ["All years", "すべての年"],
  角色: ["Characters", "キャラクター"],
  全员: ["All characters", "全員"],
  角色标签: ["Character tags", "キャラクタータグ"],
  组合筛选: ["Combination filters", "組み合わせフィルター"],
  全部组合: ["All combinations", "すべての組み合わせ"],
  偶像12人: ["12 idols", "スクールアイドル12人"],
  一年级: ["1st years", "1年生"],
  二年级: ["2nd years", "2年生"],
  三年级: ["3rd years", "3年生"],
  剧场版第一章组: ["Movie Chapter 1", "劇場版第1章組"],
  剧场版第二章组: ["Movie Chapter 2", "劇場版第2章組"],
  初始9人: ["Original 9", "初期9人"],
  动画一期10人: ["10 in Anime Season 1", "アニメ1期の10人"],
  栞子加入后10人: ["10 after Shioriko joined", "栞子加入後の10人"],
  联动时间段: ["Collaboration periods", "コラボ期間"],
  "每个时间段都需要开始、结束日期，以及标题或描述；可以添加多个时间段。": [
    "Each period needs start/end dates and a title or description; multiple periods are supported.",
    "各期間には開始日・終了日とタイトルまたは説明が必要です。複数追加できます。",
  ],
  "时间段 {count}": ["Period {count}", "期間 {count}"],
  移除时间段: ["Remove period", "期間を削除"],
  添加时间段: ["Add period", "期間を追加"],
  开始日期: ["Start date", "開始日"],
  结束日期: ["End date", "終了日"],
  时间段标题: ["Period title", "期間タイトル"],
  时间段描述: ["Period description", "期間の説明"],
  清空: ["Clear", "クリア"],
  搜索: ["Search", "検索"],
  重试: ["Retry", "再試行"],
  上一页: ["Previous page", "前のページ"],
  下一页: ["Next page", "次のページ"],
  "第 {page} / {total} 页": ["Page {page} / {total}", "{page} / {total} ページ"],
  "{count} 次联动": ["{count} collaborations", "{count} 件のコラボ"],
  "{count} 张图片": ["{count} images", "画像 {count} 枚"],
  立绘整理中: ["Illustrations being curated", "イラストを整理中"],
  "本地采集预览 · 图片已直接展示": [
    "Local collection preview · Images are shown directly",
    "ローカル収集プレビュー・画像はそのまま表示しています",
  ],
  "当前为前端预览，数据库接口尚未接入。可编辑并导出草稿，不会写入数据库。": [
    "Frontend preview: database API is not connected. Edit and export a draft; no database writes.",
    "フロントエンドのプレビューです。DB未接続のため、編集内容は下書きとして書き出せます。",
  ],
  公开预览: ["Public preview", "公開ページを確認"],
  上一联动: ["Previous collaboration", "前のコラボ"],
  下一联动: ["Next collaboration", "次のコラボ"],
  没有更早或更晚的记录: ["End of this collection", "このコレクションの端です"],
  "左右按键 / 滑动切换联动": ["Arrow keys / swipe to browse collaborations", "左右キー・スワイプでコラボを移動"],
  图片画廊: ["Illustration gallery", "イラストギャラリー"],
  查看大图: ["Enlarge image", "画像を拡大"],
  上一张图片: ["Previous image", "前の画像"],
  下一张图片: ["Next image", "次の画像"],
  查看原图: ["Open original", "原寸画像を開く"],
  图片加载失败: ["Image unavailable", "画像を読み込めませんでした"],
  关闭大图: ["Close image", "拡大表示を閉じる"],
  "图片 {number}": ["Image {number}", "画像 {number}"],
  首次公开: ["First seen", "初公開"],
  公布日期: ["Announcement", "発表日"],
  开启日期: ["Start date", "開始日"],
  合作方: ["Partners", "コラボ先"],
  版权标注: ["Credits", "権利表記"],
  相关页面: ["Related pages", "関連ページ"],
  图片来源: ["Image source", "画像の出典"],
  "来源页面（标题待补充）": ["Source page (title pending)", "出典ページ（タイトル未取得）"],
  "原 Wiki 记录": ["Original Wiki record", "元のWiki記録"],
  资料与备注: ["Details & notes", "資料・備考"],
  暂无补充说明: ["No additional notes", "補足はありません"],
  未找到联动: ["Collaboration not found", "コラボが見つかりません"],
  资料编辑: ["Record editor", "情報の編集"],
  标题: ["Title", "タイトル"],
  日期: ["Date", "日付"],
  日期含义: ["Date type", "日付の種類"],
  "合作方（每行一项）": ["Partners (one per line)", "コラボ先（1行に1件）"],
  备注: ["Notes", "備考"],
  链接标题: ["Page title", "ページタイトル"],
  添加链接: ["Add link", "リンクを追加"],
  移除: ["Remove", "削除"],
  待审核: ["Pending review", "確認待ち"],
  已审核: ["Reviewed", "確認済み"],
  审核状态: ["Review status", "確認状態"],
  设为封面: ["Set cover", "表紙に設定"],
  当前封面: ["Cover image", "現在の表紙"],
  向前移动: ["Move earlier", "前へ移動"],
  向后移动: ["Move later", "後へ移動"],
  图片说明: ["Caption", "画像の説明"],
  "添加图片 URL": ["Add image URL", "画像URLを追加"],
  上传图片: ["Upload images", "画像をアップロード"],
  "粘贴图片直链": ["Paste image URL", "画像URLを貼り付け"],
  "上传直链到 R2": ["Upload URL to R2", "URLをR2へアップロード"],
  "可直接粘贴剪贴板图片；图片直链会先抓取并上传到 R2。": ["You can paste an image from the clipboard; image URLs are fetched and uploaded to R2.", "クリップボード画像を貼り付けできます。画像URLは取得してR2へアップロードします。"],
  保存到数据库: ["Save to database", "データベースに保存"],
  "导出草稿 JSON": ["Export draft JSON", "下書きJSONを書き出す"],
  保存并审核下一条: ["Save & review next", "保存して次を確認"],
  保存成功: ["Saved", "保存しました"],
  删除联动: ["Delete collaboration", "コラボを削除"],
  "删除中……": ["Deleting…", "削除中…"],
  该联动: ["this collaboration", "このコラボ"],
  "第一次确认：确定删除「{title}」吗？": [
    "First confirmation: delete \"{title}\"?",
    "1回目の確認：「{title}」を削除しますか？",
  ],
  "第二次确认：删除「{title}」不可恢复，继续删除吗？": [
    "Second confirmation: \"{title}\" cannot be restored. Continue?",
    "2回目の確認：「{title}」は復元できません。削除を続けますか？",
  ],
  "还有未保存的修改，确定离开？": ["Leave with unsaved changes?", "未保存の変更があります。移動しますか？"],
  "请填写标题和有效日期，并补齐链接标题及网址。": [
    "Enter a title, valid date, and complete link titles and URLs.",
    "タイトル・正しい日付・リンクのタイトルとURLを入力してください。",
  ],
  "请完整填写每个时间段的开始、结束日期，以及标题或描述。": [
    "Complete each period with start/end dates and a title or description.",
    "各期間の開始日・終了日とタイトルまたは説明を入力してください。",
  ],
  "正在上传……": ["Uploading…", "アップロード中…"],
};

export function c(key, values = {}) {
  const translated = labels[key]?.[locale.value === "en" ? 0 : locale.value === "ja" ? 1 : -1];
  return translated ? translated.replace(/\{(\w+)\}/g, (_, name) => values[name] ?? `{${name}}`) : t(key, values);
}
